import { describe, expect, test } from "bun:test";
import {
	artifactId,
	assetDescription,
	assetDisplayName,
	branchChannel,
	branchFromGit,
	branchNameError,
	buildFileSource,
	strictest,
} from "../src/naming";

describe("branchFromGit", () => {
	test("uses the mapping first", () => {
		expect(branchFromGit("main", { main: "prod" })).toBe("prod");
	});
	test("lowercases and turns / into -", () => {
		expect(branchFromGit("feature/Login-Flow")).toBe("feature-login-flow");
		expect(branchFromGit("Dev")).toBe("dev");
	});
});

describe("branchNameError", () => {
	test("accepts valid names", () => {
		for (const name of ["prod", "dev", "feature-x", "release.1", "a_b", "0x"]) expect(branchNameError(name)).toBeUndefined();
	});
	test("rejects invalid names", () => {
		for (const name of ["", "Feature", "-x", "a b", "a/b", "x".repeat(65)]) expect(branchNameError(name)).toBeString();
	});
});

describe("channels", () => {
	const config = { defaultBranch: "prod", channels: { staging: "prod" as const, prod: "prod" as const } };
	test("configured channel wins", () => expect(branchChannel(config, "staging")).toBe("prod"));
	test("default branch is prod", () => expect(branchChannel({ defaultBranch: "main", channels: {} }, "main")).toBe("prod"));
	test("everything else is dev", () => expect(branchChannel(config, "feature-x")).toBe("dev"));
	test("strictest", () => {
		expect(strictest("dev", undefined)).toBe("dev");
		expect(strictest("dev", "prod")).toBe("prod");
	});
});

describe("artifactId", () => {
	test("clean", () => expect(artifactId({ channel: "dev", commit: "a1b2c3d", dirty: false })).toBe("dev-a1b2c3d"));
	test("dirty uses 6 hex of the sha256", () =>
		expect(artifactId({ channel: "prod", commit: "a1b2c3d", dirty: true, sha256: "abcdef0123" })).toBe("prod-a1b2c3d-dirty-abcdef"));
	test("no commits", () =>
		expect(artifactId({ channel: "dev", commit: "", dirty: true, sha256: "123456ff" })).toBe("dev-uncommitted-dirty-123456"));
	test("dirty without hash throws", () => expect(() => artifactId({ channel: "dev", commit: "a", dirty: true })).toThrow());
});

describe("assetDisplayName", () => {
	const base = { commit: "a1b2c3d", dirty: false, channel: "dev" as const, impliedChannel: "dev" as const };
	test("tt-<branch>-<commit>", () => expect(assetDisplayName({ ...base, branch: "main" })).toBe("tt-main-a1b2c3d"));
	test("dirty suffix", () => expect(assetDisplayName({ ...base, branch: "dev", dirty: true })).toBe("tt-dev-a1b2c3d-dirty"));
	test("channel only when it differs from the branch's", () => {
		expect(assetDisplayName({ ...base, branch: "prod", channel: "dev", impliedChannel: "prod" })).toBe("tt-prod-a1b2c3d-dev");
		expect(assetDisplayName({ ...base, branch: "prod", channel: "prod", impliedChannel: "prod" })).toBe("tt-prod-a1b2c3d");
	});
	test("only [a-z0-9-] and at most 50 chars, commit kept", () => {
		const name = assetDisplayName({ ...base, branch: "Feature.With_Odd__Chars-and-a-very-long-name-that-goes-on", dirty: true });
		expect(name).toMatch(/^[a-z0-9-]+$/);
		expect(name.length).toBeLessThanOrEqual(50);
		expect(name.endsWith("-a1b2c3d-dirty")).toBe(true);
		expect(name).not.toContain("--");
	});
	test("uncommitted", () => expect(assetDisplayName({ ...base, branch: "dev", commit: "", dirty: true })).toBe("tt-dev-uncommitted-dirty"));
});

describe("assetDescription", () => {
	test("one key=value per line", () => {
		const text = assetDescription({
			artifactId: "dev-a1b2c3d",
			commitHash: "a1b2c3d4",
			branch: "dev",
			channel: "dev",
			dirty: false,
			builtAt: "2026-10-04T00:00:00.000Z",
			sha256: "ff",
		});
		expect(text.split("\n")).toEqual([
			"artifact=dev-a1b2c3d",
			"commit=a1b2c3d4",
			"branch=dev",
			"channel=dev",
			"dirty=false",
			"built=2026-10-04T00:00:00.000Z",
			"sha256=ff",
		]);
	});
	test("ci line when present", () => {
		const text = assetDescription({ artifactId: "a", commitHash: "", branch: "b", channel: "dev", dirty: true, builtAt: "t", sha256: "s", ciUrl: "https://ci" });
		expect(text).toContain("commit=uncommitted");
		expect(text.endsWith("ci=https://ci")).toBe(true);
	});
});

test("buildFileSource is the exact generated file", () => {
	expect(buildFileSource({ dirty: false, channel: "dev", builtAt: "2026-10-04T12:00:00.000Z" })).toBe(
		[
			"// Generated by `typetorch build`. Do not edit.",
			'import { $compileTime, $git } from "rbxts-transform-debug";',
			'import type { BuildInfo } from "@typetorch/framework";',
			'const GIT = $git("Branch", "Commit");',
			'export const BUILD: BuildInfo = { branch: GIT.Branch, commit: GIT.Commit, dirty: false, channel: "dev", builtAt: $compileTime() };',
			"// 2026-10-04T12:00:00.000Z",
			"",
		].join("\n"),
	);
});
