/**
 * Per-channel debug macros (security audit S-L7). Dev-channel builds compile with the game's tsconfig.json as is, so
 * rbxts-transform-debug's `$print`/`$warn`/`$dbg`/`$assert`/`$error` keep their `[src/file.ts:line]` prefixes.
 * Prod-channel builds compile with a generated copy of it (PROD_TSCONFIG, deleted after the build) whose plugin list
 * starts with a small transformer the CLI writes into `.typetorch/` (STRIP_TRANSFORMER_FILE):
 *   $print(...), $warn(...)  removed (their arguments are not evaluated)
 *   $dbg(x)                  x (a statement `$dbg(x)` keeps only a call)
 *   $assert(c, m?)           assert(c, m?)      no source path or expression text
 *   $error(m, level?)        error(m, level?)   no source path
 * and rbxts-transform-debug itself runs with `enabled: false`.
 *
 * Why a transformer: in rbxts-transform-debug 2.2.0, `enabled` / `environmentRequires` only gate `$dbg`; `$print`,
 * `$warn`, `$error` and `$assert` always emit the source prefix (out/transform/macros/call/logging.js ignores the
 * config, despite its .d.ts comment). The template's tsconfig stays unchanged.
 *
 * Every build also gets TYPETORCH_CHANNEL and TYPETORCH_DEBUG_MACROS ("1" or "0") in the compile environment, so a
 * game can gate its own plugins with `"environmentRequires": { "TYPETORCH_DEBUG_MACROS": "1" }`.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { isRecord, parseJsonc } from "./json.ts";
import type { Channel } from "./naming.ts";

export const DEBUG_TRANSFORM = "rbxts-transform-debug";
export const STRIP_TRANSFORMER_FILE = ".typetorch/strip-debug-macros.cjs";
export const PROD_TSCONFIG = ".tsconfig.typetorch.json";
/** Bump when the transformer changes: the plugin config is part of rbxtsc's incremental-build hash. */
export const STRIP_TRANSFORMER_VERSION = 1;

/** Whether a channel's builds keep the debug macros (dev: yes, prod: no). */
export function debugMacrosFor(channel: Channel): boolean {
	return channel !== "prod";
}

/** The transformer rbxtsc loads for prod builds (CommonJS; `ts` comes from roblox-ts's plugin loader). */
export const STRIP_TRANSFORMER_SOURCE = `"use strict";
// Generated by the TypeTorch CLI for prod-channel builds (security audit S-L7). Do not edit; rewritten every build.
// Removes rbxts-transform-debug's logging macros so no debug output or source path reaches a prod payload.
const MACROS = new Set(["$print", "$warn", "$dbg", "$assert", "$error"]);
module.exports = function stripDebugMacros(program, _config, extras) {
	const ts = (extras && extras.ts) || require("typescript");
	const checker = program.getTypeChecker();
	function fromDebugModule(identifier) {
		let symbol = checker.getSymbolAtLocation(identifier);
		if (!symbol) return false;
		if (symbol.flags & ts.SymbolFlags.Alias) symbol = checker.getAliasedSymbol(symbol);
		return (symbol.declarations || []).some((d) => /[\\\\/]rbxts-transform-debug[\\\\/]/.test(d.getSourceFile().fileName));
	}
	function macroOf(node) {
		if (!ts.isCallExpression(node) || !ts.isIdentifier(node.expression)) return undefined;
		const name = node.expression.text;
		return MACROS.has(name) && fromDebugModule(node.expression) ? name : undefined;
	}
	return (context) => {
		const f = context.factory;
		// A statement in a list is dropped; the body of an if/while/for becomes an empty block (roblox-ts refuses "if (x) ;").
		const inList = (node) => !node.parent || ts.isBlock(node.parent) || ts.isSourceFile(node.parent) || ts.isModuleBlock(node.parent) || ts.isCaseOrDefaultClause(node.parent);
		const removed = (node) => (inList(node) ? undefined : f.createBlock([], false));
		const visit = (node) => {
			if (ts.isExpressionStatement(node)) {
				const name = macroOf(node.expression);
				if (name === "$print" || name === "$warn") return removed(node);
				if (name === "$dbg") {
					const arg = node.expression.arguments[0];
					return arg && ts.isCallExpression(arg) ? f.createExpressionStatement(ts.visitNode(arg, visit)) : removed(node);
				}
			}
			const name = macroOf(node);
			if (name) {
				const args = node.arguments.map((arg) => ts.visitNode(arg, visit));
				if (name === "$print" || name === "$warn") return f.createIdentifier("undefined");
				if (name === "$dbg") return args[0] || f.createIdentifier("undefined");
				return f.createCallExpression(f.createIdentifier(name === "$assert" ? "assert" : "error"), undefined, args);
			}
			return ts.visitEachChild(node, visit, context);
		};
		return (file) => ts.visitEachChild(file, visit, context);
	};
};
`;

/**
 * The prod tsconfig: the game's tsconfig.json (JSONC) with the strip transformer first and rbxts-transform-debug
 * disabled. Everything else (paths are relative to the project root, where the copy is written) stays the same.
 */
export function prodTsconfig(original: unknown): Record<string, any> {
	const config: Record<string, any> = isRecord(original) ? structuredClone(original) : {};
	const options: Record<string, any> = isRecord(config.compilerOptions) ? config.compilerOptions : {};
	const plugins: unknown[] = Array.isArray(options.plugins) ? options.plugins : [];
	options.plugins = [
		{ transform: `./${STRIP_TRANSFORMER_FILE}`, version: STRIP_TRANSFORMER_VERSION },
		...plugins.map((plugin) =>
			isRecord(plugin) && plugin.transform === DEBUG_TRANSFORM ? { ...plugin, enabled: false } : plugin,
		),
	];
	config.compilerOptions = options;
	return config;
}

export function readTsconfig(root: string): unknown {
	const path = join(root, "tsconfig.json");
	if (!existsSync(path)) return {};
	return parseJsonc(readFileSync(path, "utf8"));
}

/** True when a package.json build script ends with an rbxtsc call, so `-p <tsconfig>` can be appended to it. */
export function scriptEndsWithRbxtsc(script: string): boolean {
	return /(?:^|&&|\|\||;)\s*(?:bunx\s+|npx\s+)?rbxtsc(?:\s+[^&|;]*)?\s*$/.test(script.trim());
}
