/**
 * The Lune script `kernel deploy` runs (Lune 0.10, `@lune/roblox`, rbx-dom): written to the state dir and run with
 * `lune run <file> <mode> <args...>` in the kernel dir (its rokit.toml pins Lune). Kept as a string so the npm
 * package ships it inside dist/.
 *
 *   verify <original.rbxl> <patched.rbxl> <kernel.rbxl> <spec.json> <out.json>
 *     An independent check of a patch, through rbx-dom instead of the CLI's own binary reader:
 *     - every service of the original exists in the patched place, and its own properties are equal (the service is
 *       cloned without children and serialized; the settings the patch applies are applied to the original's copy);
 *     - every top-level child outside the slots is equal: same order, names and classes, and the same sha256 of
 *       `serializeModel({child})` (the whole subtree, every property rbx-dom reads); when only the hash differs, a
 *       property-by-property comparison decides (a class that gained a property chunk holds explicit defaults:
 *       counted in stats.explicitDefaults, not a problem);
 *     - every referent property outside the slots points where it pointed before (by full name; a change is listed
 *       under "references", never silently: the CLI expects exactly the references it cleared);
 *     - each slot equals the kernel build's: per instance path, class, Source hash, attributes, tags, Disabled,
 *       RunContext;
 *     - the settings (spec.settings) have the kernel build's values.
 *     Writes a JSON report; exits 0 either way (the report says ok or not).
 *
 *   patch <original.rbxl> <kernel.rbxl> <spec.json> <out.rbxl>
 *     The `--engine lune` patch: deserializePlace, destroy the slots, clone the kernel build's slots in, copy the
 *     settings, serializePlace. Re-encodes the whole place through rbx-dom (property migrations and drops apply: see
 *     placepatch.ts), so it is only the fallback when the splice engine refuses.
 *
 * spec.json: {"slots":[{"service":"ServerScriptService","name":"TypeTorchKernel"},...],
 *             "settings":[{"service":"ServerScriptService","prop":"LoadStringEnabled"},...]}
 */
export const KERNEL_PATCH_LUAU = String.raw`--!nocheck
-- Generated by the TypeTorch CLI (src/kernelpatch-luau.ts). Safe to delete.
local roblox = require("@lune/roblox")
local fs = require("@lune/fs")
local serde = require("@lune/serde")
local process = require("@lune/process")

local args = process.args
local mode = args[1]

local function readPlace(path)
	return roblox.deserializePlace(fs.readFile(path))
end

local function slotSet(spec)
	local set = {}
	for _, slot in spec.slots do
		set[slot.service .. "\0" .. slot.name] = true
	end
	return set
end

local function isSlot(set, service, child)
	return set[service.ClassName .. "\0" .. child.Name] == true
end

-- FindService errors for classes rbx-dom doesn't know as services (some top-level children are plain "Instance").
local function findService(game, className)
	local ok, service = pcall(function()
		return game:FindService(className)
	end)
	if ok then
		return service
	end
	return nil
end

local function findSlot(game, slot)
	local service = findService(game, slot.service)
	if service == nil then
		return nil
	end
	return service:FindFirstChild(slot.name)
end

local function sha(bytes)
	return serde.hash("sha256", bytes)
end

local function sortedAttributes(instance)
	local keys = {}
	local attributes = instance:GetAttributes()
	for key in attributes do
		table.insert(keys, key)
	end
	table.sort(keys)
	local parts = {}
	for _, key in keys do
		table.insert(parts, key .. "=" .. typeof(attributes[key]) .. ":" .. tostring(attributes[key]))
	end
	return table.concat(parts, ";")
end

local function tryProp(instance, name)
	local ok, value = pcall(function()
		return instance[name]
	end)
	if ok then
		return tostring(value)
	end
	return "-"
end

local function describe(root)
	local lines = {}
	local base = root:GetFullName()
	local function add(instance)
		local rel = instance:GetFullName():sub(#base + 1)
		local source = "-"
		if instance:IsA("LuaSourceContainer") then
			source = sha(instance.Source)
		end
		local tags = instance:GetTags()
		table.sort(tags)
		table.insert(lines, table.concat({
			rel,
			instance.ClassName,
			source,
			sortedAttributes(instance),
			table.concat(tags, ","),
			if instance:IsA("BaseScript") then tryProp(instance, "Disabled") .. "/" .. tryProp(instance, "RunContext") else "-",
		}, "|"))
	end
	add(root)
	for _, descendant in root:GetDescendants() do
		add(descendant)
	end
	table.sort(lines)
	return lines
end

-- Referent properties of a class (and its superclasses), from rbx-dom's reflection database.
local database = roblox.getReflectionDatabase()
local refPropsCache = {}
local function refProps(className)
	local cached = refPropsCache[className]
	if cached then
		return cached
	end
	local names = {}
	local class = database:GetClass(className)
	while class do
		for name, prop in class.Properties do
			if tostring(prop.Datatype) == "Ref" then
				table.insert(names, name)
			end
		end
		class = if class.Superclass then database:GetClass(class.Superclass) else nil
	end
	refPropsCache[className] = names
	return names
end

local function targetName(instance, prop)
	local ok, value = pcall(function()
		return instance[prop]
	end)
	if not ok or value == nil then
		return "nil"
	end
	return value:GetFullName()
end

-- Every non-referent property rbx-dom knows for a class (and its superclasses).
local valuePropsCache = {}
local function valueProps(className)
	local cached = valuePropsCache[className]
	if cached then
		return cached
	end
	local names = {}
	local class = database:GetClass(className)
	while class do
		for name, prop in class.Properties do
			if tostring(prop.Datatype) ~= "Ref" then
				table.insert(names, name)
			end
		end
		class = if class.Superclass then database:GetClass(class.Superclass) else nil
	end
	table.sort(names)
	valuePropsCache[className] = names
	return names
end

local function valueOf(instance, prop)
	local ok, value = pcall(function()
		return instance[prop]
	end)
	if not ok then
		return "<unreadable>"
	end
	return typeof(value) .. ":" .. tostring(value)
end

-- Two subtrees whose serializations differ can still be equal: a class that gained a property chunk in the patched
-- file (the kernel's instances set it) holds explicit default values where the original had none. Compare what
-- rbx-dom reads instead: class, name, every known property (absent = default), attributes and tags, per instance.
-- Returns the first difference, or nil.
local function firstDifference(a, b)
	local listA, listB = a:GetDescendants(), b:GetDescendants()
	table.insert(listA, 1, a)
	table.insert(listB, 1, b)
	if #listA ~= #listB then
		return #listA .. " instances before, " .. #listB .. " after"
	end
	for i, x in listA do
		local y = listB[i]
		if x.ClassName ~= y.ClassName or x.Name ~= y.Name then
			return x:GetFullName() .. " became " .. y:GetFullName() .. " (" .. y.ClassName .. ")"
		end
		for _, prop in valueProps(x.ClassName) do
			local before, after = valueOf(x, prop), valueOf(y, prop)
			if before ~= after then
				return x:GetFullName() .. "." .. prop .. ": " .. before .. " -> " .. after
			end
		end
		if sortedAttributes(x) ~= sortedAttributes(y) then
			return x:GetFullName() .. ": attributes differ"
		end
		local tagsA, tagsB = x:GetTags(), y:GetTags()
		table.sort(tagsA)
		table.sort(tagsB)
		if table.concat(tagsA, ",") ~= table.concat(tagsB, ",") then
			return x:GetFullName() .. ": tags differ"
		end
	end
	return nil
end

-- Every referent property in two equal-shaped subtrees: where it points (by full name), before and after.
local function compareRefs(a, b, out)
	local listA, listB = a:GetDescendants(), b:GetDescendants()
	table.insert(listA, 1, a)
	table.insert(listB, 1, b)
	if #listA ~= #listB then
		return
	end
	for i, x in listA do
		local y = listB[i]
		if x.ClassName == y.ClassName then
			for _, prop in refProps(x.ClassName) do
				local before, after = targetName(x, prop), targetName(y, prop)
				if before ~= after then
					table.insert(out, x:GetFullName() .. "." .. prop .. ": " .. before .. " -> " .. after)
				end
			end
		end
	end
end

-- A service without its children (its own properties only); with settings, those copied from the kernel build.
local function serviceCopy(service, settings, source)
	local copy = service:Clone()
	copy:ClearAllChildren()
	if settings ~= nil then
		for _, setting in settings do
			if setting.service == service.ClassName then
				copy[setting.prop] = source[setting.prop]
			end
		end
	end
	return copy
end

if mode == "verify" then
	local original = readPlace(args[2])
	local patched = readPlace(args[3])
	local kernel = readPlace(args[4])
	local spec = serde.decode("json", fs.readFile(args[5]))
	local slots = slotSet(spec)
	local problems = {}
	local references = {}
	local stats = { services = 0, subtrees = 0, instances = 0, explicitDefaults = 0 }

	-- Top-level children pair up by position: a patch keeps their order and appends any service it adds.
	local patchedTop = patched:GetChildren()
	for index, service in original:GetChildren() do
		local other = patchedTop[index]
		if other == nil or other.ClassName ~= service.ClassName or other.Name ~= service.Name then
			table.insert(problems, "top-level child " .. index .. " (" .. service.Name .. ", " .. service.ClassName .. ") is missing or moved")
			continue
		end
		stats.services += 1
		local kernelService = findService(kernel, service.ClassName)
		local want, got = serviceCopy(service, spec.settings, kernelService), serviceCopy(other, nil, nil)
		if sha(roblox.serializeModel({ want })) ~= sha(roblox.serializeModel({ got })) then
			local difference = firstDifference(want, got)
			if difference then
				table.insert(problems, "service " .. service.ClassName .. ": " .. difference)
			else
				stats.explicitDefaults += 1
			end
		end
		local before, after = {}, {}
		for _, child in service:GetChildren() do
			if not isSlot(slots, service, child) then
				table.insert(before, child)
			end
		end
		for _, child in other:GetChildren() do
			if not isSlot(slots, other, child) then
				table.insert(after, child)
			end
		end
		if #before ~= #after then
			table.insert(problems, service.ClassName .. ": " .. #before .. " children outside the slots before, " .. #after .. " after")
		end
		for i = 1, math.min(#before, #after) do
			local a, b = before[i], after[i]
			stats.subtrees += 1
			stats.instances += 1 + #a:GetDescendants()
			if a.Name ~= b.Name or a.ClassName ~= b.ClassName then
				table.insert(problems, service.ClassName .. " child " .. i .. ": " .. a.Name .. " (" .. a.ClassName .. ") became " .. b.Name .. " (" .. b.ClassName .. ")")
			else
				-- The subtree's own content (references leaving it serialize as nil), then where its references point.
				if sha(roblox.serializeModel({ a })) ~= sha(roblox.serializeModel({ b })) then
					local difference = firstDifference(a, b)
					if difference then
						table.insert(problems, a:GetFullName() .. " (" .. a.ClassName .. "): " .. difference)
					else
						stats.explicitDefaults += 1
					end
				end
				compareRefs(a, b, references)
			end
		end
	end
	local addedServices = {}
	for index = #original:GetChildren() + 1, #patchedTop do
		table.insert(addedServices, patchedTop[index].ClassName)
	end

	local slotReports = {}
	for _, slot in spec.slots do
		local want = findSlot(kernel, slot)
		local got = findSlot(patched, slot)
		local entry = { slot = slot.service .. "." .. slot.name, instances = 0, equal = false }
		if want == nil then
			table.insert(problems, entry.slot .. ": not in the kernel build")
		elseif got == nil then
			table.insert(problems, entry.slot .. ": missing after the patch")
		else
			local a, b = describe(want), describe(got)
			entry.instances = #b
			entry.equal = #a == #b
			if entry.equal then
				for i = 1, #a do
					if a[i] ~= b[i] then
						entry.equal = false
						table.insert(problems, entry.slot .. ": differs from the kernel build at " .. b[i])
						break
					end
				end
			else
				table.insert(problems, entry.slot .. ": " .. #b .. " instances, the kernel build has " .. #a)
			end
		end
		table.insert(slotReports, entry)
	end

	local settings = {}
	for _, setting in spec.settings do
		local got = findService(patched, setting.service)
		local want = findService(kernel, setting.service)
		local value = if got then tryProp(got, setting.prop) else "-"
		local expected = if want then tryProp(want, setting.prop) else "-"
		if value ~= expected then
			table.insert(problems, setting.service .. "." .. setting.prop .. " is " .. value .. ", the kernel build has " .. expected)
		end
		table.insert(settings, { path = setting.service .. "." .. setting.prop, value = value })
	end

	local identity = {}
	local kernelFolder = findSlot(patched, { service = "ServerScriptService", name = "TypeTorchKernel" })
	if kernelFolder then
		for _, key in { "KernelVersion", "KernelHash", "KernelCommit", "KeyAssetId", "FallbackPublicKey", "BootstrapHeads" } do
			local value = kernelFolder:GetAttribute(key)
			if value ~= nil then
				identity[key] = tostring(value)
			end
		end
	end

	fs.writeFile(args[6], serde.encode("json", {
		ok = #problems == 0,
		problems = problems,
		references = references,
		stats = stats,
		addedServices = addedServices,
		slots = slotReports,
		settings = settings,
		identity = identity,
	}))
elseif mode == "patch" then
	local game = readPlace(args[2])
	local kernel = readPlace(args[3])
	local spec = serde.decode("json", fs.readFile(args[4]))
	local removed, added = 0, 0
	for _, slot in spec.slots do
		local service = game:GetService(slot.service)
		for _, child in service:GetChildren() do
			if child.Name == slot.name then
				removed += 1 + #child:GetDescendants()
				child:Destroy()
			end
		end
		local source = findSlot(kernel, slot)
		if source == nil then
			error("the kernel build has no " .. slot.service .. "." .. slot.name)
		end
		local copy = source:Clone()
		added += 1 + #copy:GetDescendants()
		copy.Parent = service
	end
	for _, setting in spec.settings do
		game:GetService(setting.service)[setting.prop] = kernel:GetService(setting.service)[setting.prop]
	end
	fs.writeFile(args[5], roblox.serializePlace(game))
	print(serde.encode("json", { removed = removed, added = added }))
else
	error("usage: lune run kernel-patch.luau verify|patch ...")
end
`;
